create table ADDRESS (

AddressID NUMBER(9) PRIMARY KEY NOT NULL,
Street VARCHAR2(20) NOT NULL,
Unit_Number VARCHAR(5) NOT NULL,
City VARCHAR2(20) NOT NULL,
State VARCHAR2(2) NOT NULL,
Country VARCHAR2(20) NOT NULL,
Zip VARCHAR2(10) NOT NULL

);
