create table VACCINATION (

VaccinationID NUMBER(9) PRIMARY KEY NOT NULL,
PatientID NUMBER(9) NOT NULL,
VaccineID NUMBER(9) NOT NULL,
VaccinatorID NUMBER(9) NOT NULL,
Date_Taken DATE,
Route VARCHAR2(20) NOT NULL,
Site VARCHAR2(20) NOT NULL,
Date_Of_Next DATE,

Constraint VACCINATION_UQ UNIQUE (PatientID, VaccineID, VaccinatorID)
);

INSERT into VACCINATION values (
1,
1,
1,
1,
TO_DATE('23-MAY-2005', 'DD-MON-YYYY'),
'IM',
'UA',
TO_DATE('23-MAY-2020', 'DD-MON-YYYY')
);